export default {
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    LOG_OUT: "LOG_OUT",

    STORE_USERS_LIST: 'STORE_USERS_LIST',
    
    SAVE_USERNAME: "SAVE_USERNAME",
    SAVE_PROFILE_IMAGE: "SAVE_PROFILE_IMAGE",
    SAVE_USER_DESCRIPTION: "SAVE_USER_DESCRIPTION",
    SAVE_USER_LOCATION: "SAVE_USER_LOCATION",
    SAVE_USER_EMAIL: "SAVE_USER_EMAIL",
    SAVE_GALLERY_IMAGE: "SAVE_GALLERY_IMAGE",
    DELETE_GALLERY_IMAGE: "DELETE_GALLERY_IMAGE",
    SAVE_BIO: 'SAVE_BIO',
    SAVE_PHONE_NUMBER: "SAVE_PHONE_NUMBER"
}